config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customer/dashboard" , controller: :customers , action: :dashboard , as: :cust_dashboard
    get "/seller/dashboard" , controller: :sellers , action: :dashboard , as: :seller_dashboard
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    get "/address/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions", controller: :claim_resolutions , action: :update 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims ,:addresses
  resources :claim_resolutions


  namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customers/customer_invoices" , controller: :customers , action: :customer_invoices , as: :cutomer_invoices
    get "/sellers/seller_products" , controller: :sellers , action: :seller_products , as: :seller_products
    get "/sellers/stats" , controller: :sellers , action: :stats , as: :stats
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    patch "/addresses/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions/default_claim_resolution" ,controller: :claim_resolutions,action: :default_claim_resolution,as: :default_claim_resolution
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims  ,:addresses
  resources :claim_resolutions
  end


end

app/models/claim_resolution.rb
class ClaimResolution < ApplicationRecord
  belongs_to :warranty_claim 
  has_one :invoice, through: :warranty_claim 
  validates :status, :description , presence: true
  validates :description , length: {minimum: 10, maximum: 1000}
  #where(status: ["Accepted", "In Progress"])
  scope :pending, -> { ClaimResolution.where(status:  ["Accepted","In Progress","Shipped"]) }
  scope :resolved, -> { ClaimResolution.where(status:  ["Rejected","Closed"]) }


  before_create :set_resolution_description


    
  def set_resolution_description 
      self.description = "Our Team will Validate your claim"
  end
end

app/controllers/api/claim_resolutions_controller.rb
class Api::ClaimResolutionsController< Api::ApiController
   before_action :set_claim_resolution, only: %i[ show update destroy ]
   # GET /claim_resolutions or /claim_resolutions.json
    def index
      claim_resolutions = current_user.userable.claim_resolutions
      if claim_resolutions
        render json: claim_resolutions, status: 200 #ok
      else
         render json: {message: "No Claim Resolutions Found"}, status:204 #no_content
      end
    end
  
    # GET /claim_resolutions/1 or /claim_resolutions/1.json
    def show

      if current_user.userable.claim_resolutions.include?(@claim_resolution)
        render json: @claim_resolution , status:200 #ok
     else
      render json:{message:"Forbidden Access to the profile"}, status:403 #forbidden
     end
    end
  
    
  
    # POST /claim_resolutions or /claim_resolutions.json
    def create
      warranty_claim=WarrantyClaim.find_by(id: params[:claim_resolution][:warranty_claim_id])
      if current_user.seller? && current_user.userable.warranty_claims.include?(warranty_claim)
        claim_resolution = ClaimResolution.new(claim_resolution_params)
        if (claim_resolution.save)
          render json:claim_resolution, status: 200#created
        else
          render json:{error: claim_resolution.errors.full_messages},  status:422 #unprocessable_entity
        end
      else
        render json:{message:"Forbidden Access to create the claim resolution"}, status:403 #forbidden
      end
      
    end
  
    # PATCH/PUT /claim_resolutions/1 or /claim_resolutions/1.json
    def update
      if current_user.seller? && current_user.userable.claim_resolutions.include?(@claim_resolution)
        if(@claim_resolution.update(claim_resolution_params))
           render json:@claim_resolution, status: 200#accepted
        else
           render json:{error: @claim_resolution.errors.full_messages}, status:422 #unprocessable_entity
         end
      else
        render json:{message:"Forbidden Access to update the Claim Resolution"}, status:403 #forbidden
      end
      
    end
  
    # DELETE /claim_resolutions/1 or /claim_resolutions/1.json
    def destroy
      if current_user.seller? && current_user.userable.claim_resolutions.include?( @claim_resolution)
        if @claim_resolution.destroy
          render json:{ message: "Claim Resolution Deleted successfully"},status:200 #ok
        else
          render json:{error: @claim_resolution.errors.full_messages}, status:422#unprocessable_entity
        end

      else
        render json:{error: "Fobidden Access to delete the claim resolution"}, status: 403
      end
    end
    
    def default_claim_resolution
      
      claim_resolution = ClaimResolution.find_by(id: params[:claim_resolution_id])
      if claim_resolution
        if current_user.seller? && current_user.userable.claim_resolutions.include?(claim_resolution)
          claim_resolution.status="In Progress"
          claim_resolution.description="Our Team will Validate your claim"
          claim_resolution.save
          render json:claim_resolution, status:200
        
        else
          render json:{error: "Fobidden Access to reset the Claim Resolution"}, status: 403
         end
      else
        render json:{error: "No Claim Resolution found with Id #{params[:id]}"}, status: 404
      end
    end 

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_claim_resolution
        @claim_resolution = ClaimResolution.find_by(id: params[:id])
        if !@claim_resolution
          render json:{error: "No Claim Resolution found with Id #{params[:id]}"}, status: 404
          return 
        end
      end
  
      # Only allow a list of trusted parameters through.
      def claim_resolution_params
        params.fetch(:claim_resolution, {  }).permit( :warranty_claim_id , :status , :description )
      end



end

app/controllers/claim_resolutions_controller.rb
class ClaimResolutionsController < ApplicationController
    before_action :set_claim_resolution, only: %i[ show edit update destroy ]
    before_action :authenticate_user! 
    before_action :authorize_seller, only: %i[ new edit destroy ]
   # GET /claim_resolutions or /claim_resolutions.json
    def index

      @claim_resolutions = current_user.userable.claim_resolutions
    end
  
    # GET /claim_resolutions/1 or /claim_resolutions/1.json
    def show
      unless current_user.userable.claim_resolutions.include?(@claim_resolution)
        
        redirect_to root_path
        flash[:notice] = "You are not authorized."
        return
      end
    end
  
    # GET /claim_resolutions/new
    def new
      @claim_resolution = ClaimResolution.new
    end
  
    # GET /claim_resolutions/1/edit
    def edit
      unless current_user.userable.claim_resolutions.include?(@claim_resolution)
        flash[:notice] = "You are not authorized."
        redirect_to root_path
        return
      end
    end
  
    # POST /claim_resolutions or /claim_resolutions.json
    def create
       warranty_claim=WarrantyClaim.find_by(id: params[:claim_resolution][:warranty_claim_id])
      unless current_user.userable.warranty_claims.include?(warranty_claim)
        flash[:notice] = "You are not authorized ."
        redirect_to root_path
        return
      end
      @claim_resolution = ClaimResolution.new(claim_resolution_params)
  
      respond_to do |format|
        if @claim_resolution.save
          format.html { render :index, notice: "Claim status was successfully created." }
          format.json { render :show, status: :created, location: claim_resolution }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @claim_resolution.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /claim_resolutions/1 or /claim_resolutions/1.json
    def update
      respond_to do |format|
        if @claim_resolution.update(claim_resolution_params)
          format.html { redirect_to claim_resolution_url(@claim_resolution), notice: "Claim status was successfully updated." }
          format.json { render :show, status: :ok, location: @claim_resolution }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @claim_resolution.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /claim_resolutions/1 or /claim_resolutions/1.json
    def destroy
      flash[:alert]="It is Not advisable to delete resolution"
      @claim_resolution.destroy
  
      respond_to do |format|
        format.html { redirect_to claim_resolutions_url, notice: "Claim status was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_claim_resolution
        @claim_resolution = ClaimResolution.find_by(id: params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def claim_resolution_params
        params.require(:claim_resolution).permit( :warranty_claim_id , :status , :description )
      end

      def authorize_seller
        unless  (user_signed_in? && current_user.seller?)
          flash[:alert] = "You are not authorized ."
          redirect_to root_path
          return
        end
      end


end

app/helpers/claim_resolutions_helper.rb
module ClaimResolutionsHelper
end

app/views/claim_resolutions/_form.html.erb
<div class="col-lg-10" >
<%= form_with(model: @claim_resolution) do |form| %>
  <% if @claim_resolution.errors.any? %>
    <div id="error_explanation">
      
      <ul>
        <% @claim_resolution.errors.each do |error| %>
            <%flash.now[:alert]=error.full_message%>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :Warranty_claim_id %>
    <%= form.text_field :warranty_claim_id ,class:"form-control"%>
</div>
<div class="form-group">
     <%= form.label :status %>
     <%= form.text_field :status,class:"form-control" %>
</div>
<div class="form-group">
     <%= form.label :Description %>
     <%= form.text_field :description ,class:"form-control"%>
</div>


  <div class="actions">
   <%= link_to 'Back', :back, class: 'btn btn-secondary' %>

<%=form.submit "Update" , class: "btn btn-primary" , style:"margin-left: 20px"%>
  </div>
<% end %>
</div>

app/views/claim_resolutions/edit.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">Edit Claim Resolution</h1>
<div class="col-lg-10" >
<%= form_with(model: @claim_resolution) do |form| %>
  <% if @claim_resolution.errors.any? %>
    <div id="error_explanation">
      

      <ul>
        <% @claim_resolution.errors.each do |error| %>
           <%flash.now[:alert]=error.full_message%>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="form-group">
    <strong> <%= form.label :status,"Status  :" %> </strong> 
    <%= form.select :status, options_for_select([['In Progress', 'In Progress'], ['Accepeted', 'Accepted'], ['Rejected', 'Rejected'], ['Shipped', 'Shipped'], ['Closed', 'Closed']]), { :multiple => false, include_blank: 'Select'}, {class: "form-select shadow shadow-sm ", required: true} %>
    <%
=begin%>
 # <%= form.select :status, %> 
<%
=end%>
</div>
<div class="form-group">
   <strong>   <%= form.label :Description, "Description  :" %></strong> 
     <%= form.text_field :description ,class:"form-control"%>
</div>


  <div class="actions">
  <%= link_to 'Back', :back, class: 'btn btn-secondary' %>

<%=form.submit "Update" , class: "btn btn-primary" , style:"margin-left: 20px"%>
  </div>
<% end %>
</div>


</div>
</div>

app/views/claim_resolutions/index.html.erb
<div class="container">
<div class="col-lg-25">
  <br>
  <h1 class="mb-3">Claim Resolutions</h1>
<%if @claim_resolutions.size != 0%>
  <table class="table mt-3">
    <thead class="thead-dark">
      <tr>
        <th > S.No</th>
        <th> Customer</th>
        <th>Product Name</th>
        <th>Update On</th>
        <th>Status</th>
        <th>Problem Description</th>
        <th colspan="2">Actions</th>

      </tr>
    </thead>

    <tbody>
      <% @claim_resolutions.each do |claim_resolution| %>
        <tr class="table-active">
          <td><%= @claim_resolutions.find_index(claim_resolution)+1 %></td>
           <td><%= claim_resolution.warranty_claim.invoice.customer.name %></td>
          <td><%= claim_resolution.warranty_claim.invoice.product.name %></td>
          <td><%= claim_resolution.updated_at.to_date %></td>
          <td><%= claim_resolution.status %></td>
          <td><%= claim_resolution.warranty_claim.problem_description %></td>
          <td><%= link_to 'Show', claim_resolution, class: 'btn btn-primary' %></td>
          
          <td><%= link_to 'Edit', edit_claim_resolution_path(claim_resolution), class: 'btn btn-primary' %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <%else%>
     
       <h4> No Claim Resolutions Found !!</h4>
    <%end%>

  <br>
</div>
</div>

app/views/claim_resolutions/new.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">New Claim Resolution</h1>

<%= render 'form', claim_resolution: @claim_resolution %>



</div>
</div>

app/views/claim_resolutions/show.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px; color: #fff;">
  <p id="notice" style="color: #fff;"><%= notice %></p>
  <h4><p><strong> Resolver:</strong> <%= @claim_resolution.warranty_claim.invoice.product.seller.name %></p></h4>
  <h4><p><strong>Organisation:</strong> <%= @claim_resolution.warranty_claim.invoice.product.seller.organisation_name %></p></h4>
  <h4><p><strong>Status:</strong> <%= @claim_resolution.status %></p></h4>
  <h4><p><strong>Description:</strong> <%= @claim_resolution.description %></p></h4>
  <h4><p><strong>Last Updated:</strong> <%= @claim_resolution.updated_at %></p></h4>

  <% if current_user.seller? %>
    <%= link_to 'Edit', edit_claim_resolution_path(@claim_resolution), class: 'btn btn-primary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;' %> 
    <%= link_to 'Back', seller_dashboard_path, class: 'btn btn-secondary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;' %>
  <% elsif current_user.customer? %>
    <%= link_to 'Back', cust_dashboard_path, class: 'btn btn-secondary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;' %>
  <% end %>
</div>
</div>