config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customer/dashboard" , controller: :customers , action: :dashboard , as: :cust_dashboard
    get "/seller/dashboard" , controller: :sellers , action: :dashboard , as: :seller_dashboard
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    get "/address/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions", controller: :claim_resolutions , action: :update 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims ,:addresses
  resources :claim_resolutions


  namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customers/customer_invoices" , controller: :customers , action: :customer_invoices , as: :cutomer_invoices
    get "/sellers/seller_products" , controller: :sellers , action: :seller_products , as: :seller_products
    get "/sellers/stats" , controller: :sellers , action: :stats , as: :stats
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    patch "/addresses/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions/default_claim_resolution" ,controller: :claim_resolutions,action: :default_claim_resolution,as: :default_claim_resolution
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims  ,:addresses
  resources :claim_resolutions
  end


end

app/models/seller.rb
class Seller < ApplicationRecord
    has_and_belongs_to_many :customers ,join_table: :customers_sellers
    has_many :products , dependent: :destroy
    has_many :addresses, as: :addressable, dependent: :destroy
    has_many :invoices, through: :products
    has_many :warranty_claims, through: :invoices
    has_many :claim_resolutions, through: :warranty_claims
    has_one :user, as: :userable , dependent: :destroy
   
    validates :name , :email,:phone_no , presence: true
    validates :phone_no ,length: {is: 10},numericality: true ,presence: true,format:{ with: /[9876]{1}\d{9}/, message: 'please enter a valid phone number' }
    validates :email ,uniqueness: true , format:{with: /\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+/, message: 'please enter a valid email' }
    validates :name ,length: {minimum: 1, maximum: 25}
    validates :name, format: { with: /\A[A-Za-z\s.\-]+\z/, message: "only allows alphabets, spaces, dots, and hyphens" }
    validates :organisation_name, presence: true
    validates :designation , presence: true


    scope :has_sold, -> { joins(:invoices).distinct }
    scope :not_sold, -> { left_outer_joins(:invoices).where(invoices: { id: nil }) }
end

app/controllers/api/sellers_controller.rb
class Api::SellersController < Api::ApiController
   before_action :set_seller, only: %i[show  update destroy]
      #show all the seller in DB
    def index 
        sellers=Seller.all
        if sellers
          render json: sellers, status: 200 #ok
          else
           render json: {message: "No Sellers Found"}, status:204 #no_content
          end
    end
  
  #used to insert the new record in DB
    def create
        seller = Seller.new(seller_params)
        
        if(seller.save)
            render json:seller , status: 200#created
        else
            render json:{error: seller.errors.full_messages},status:422 #unprocessable_entity
        end

    end
 
    def show
        if @seller.id == current_user.userable_id
           render json: @seller , status:200 #ok

         else
           render json:{message:"Unauthorised Access to the profile"}, status:403 
       end
     end
       

  #saves the changes to DB
    def update
      
        if @seller.id==current_user.userable_id && current_user.seller?
      
          if(@seller.update(seller_params))
            render json:@seller , status:200#accepted
          else
            render json:{error: @seller.errors.full_messages}, status:422 #unprocessable_entity
           end
        else
          render json:{message:"Unauthorised Access to update the profile"}, status:403 
        end
     
    end
  #deletes a record from DB
    def destroy
       
     if @seller &&  @seller.id==current_user.userable_id && current_user.seller?
         
           if(@seller.destroy)
             render json:{ message: "Seller Deleted successfully"},status:200 #ok
           else
             render json:{error: @seller.errors.full_messages}, status:422#unprocessable_entity
            end
        

      else

        render json:{message:"Unauthorised Access to delete the profile"}, status:403 


      end
      
    end

    
    def seller_products
      seller = Seller.find_by(id: current_user.userable_id )
      
        if seller && current_user.seller?
          products = Product.where(seller_id: current_user.userable_id )
          if products
            render json: products , status:200
          else
             render json:{message:"No products For given Seller Id #{params[:id]}"},status:204 #no_content

          end  
        else
          render json:{message:"Unauthorised Access to the profile"}, status:403 
        end
      
    end

    def stats  
      if current_user.seller?
        customer_count = current_user.userable.customers.distinct.count
        product_count = current_user.userable.products.distinct.count
        invoice_count = current_user.userable.invoices.distinct.count
       render json:{ customer_reached: customer_count, product_listed: product_count, product_sold: invoice_count  } , status:200
      
      else
        render json:{message:"Unauthorised Access "}, status:403 
      end


    end
        
    
    

 private
    def set_seller
        @seller =Seller.find_by(id: params[:id])
        if !@seller
          render json:{error:"No seller found with given Id #{params[:id]}"}, status:404
          return
        end

    end
    def seller_params
        params.require( :seller).permit(:name, :email,:organisation_name,:designation,:description,:primary_address_id,:phone_no)
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
   before_action :set_seller, only: %i[show edit update destroy]
   #before_action :authenticate_user!
   before_action :authorize_seller, only: %i[  edit destroy dashboard]
      #show all the seller in DB
    def index 
        @sellers=Seller.all
    end
  #used to instantiate a seller
    def new
        @seller=Seller.new
    end
  #used to insert the new record in DB
    def create
        @seller=Seller.new(seller_params)
        if(@seller.save)
            redirect_to sellers_path
        else
            render :new
        end

    end
  #used to display a particular record
    def show
      unless current_user.userable == (@seller)
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to root_path
      end
    end
  #used to fetch the record to edit
    def edit
      unless current_user.userable == (@seller)
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to root_path
      end
    end
  #saves the changes to DB
    def update
        if(@seller.update(seller_params))
            render :show
        else
            render :edit 
        end
    end
  #deletes a record from DB
    def destroy
      unless current_user.userable == (@seller)
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to root_path
      end
        if(@seller.destroy)
            redirect_to sellers_path
        else
            render :edit 
        end
    end

    
    def dashboard
        # @seller = Seller.find(current_user.userable.id)
       # @products = current_user.userable.products
       @customer_count = current_user.userable.customers.distinct.count
       @product_count = current_user.userable.products.distinct.count
       @invoice_count = current_user.userable.invoices.distinct.count
      #  p"==========="
      #  p @customer_count
        @warranty_claims = current_user.userable.warranty_claims.where.not(claim_resolution: ClaimResolution.where(status: ["Closed", "Rejected"]))


      

        # p @warranty_claims
       
       
      
      end
        
    
    

 private
    def set_seller
        @seller=Seller.find_by(id: params[:id])
    end
    def seller_params
        params.require( :seller).permit(:name, :email,:organisation_name,:designation,:description)
    end

    def authorize_seller
      unless (user_signed_in? && current_user.seller?)
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to root_path
      end
    end

end

app/views/sellers/_form.html.erb
<%if @seller.errors.any?%>
    <% @seller.errors.full_messages.each do|message| %>
      <%flash.now[:alert]=message%>
    <%end%>
 <%end%>
<%=form_with model: @seller do|form|%>
<div class="form-group">
    <%= form.label :Name %>
    <%= form.text_field :name ,class: "form-control" %>
</div>
<div class="form-group">
     <%= form.label :Email %>
     <%= form.email_field :email ,class: "form-control" %>
</div>
<div class="form-group">
     <%= form.label :Organisation %>
     <%= form.text_field :organisation_name ,class: "form-control" %>
</div>
<div class="form-group">
     <%= form.label :Designation %>
     <%= form.text_field :designation ,class: "form-control" %>
</div>
<%=form.submit %>
<%end%>

app/views/sellers/dashboard.html.erb
<div class="container">
  <h1 class="mt-4">Welcome to the Seller Dashboard</h1>
  <style>
    .card {
      width: 17rem;
    }
    .card-title {
      font-size: 1.5rem;
    }
    .card-text {
      font-size: 3rem;
      font-weight: bold;
      text-align: center;
      margin-top: 1rem;
    }
  </style> 
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card bg-success text-white mb-3">
          <div class="card-body">
            <h5 class="card-title"> Customers Reached</h5>
            <p class="card-text text-center"><%= @customer_count %></p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card bg-success text-white mb-3">
          <div class="card-body">
       
            <h5 class="card-title">Listed Products</h5>
            <p class="card-text text-center"><%= @product_count %></p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card bg-success text-white mb-3">
          <div class="card-body">
            <h5 class="card-title">Sold Products</h5>
            <p class="card-text text-center"><%= @invoice_count %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Add New Product', new_product_path, class: 'btn btn-success mt-4' %>

  <h2 class="mt-4">Warranty Claims</h2>
  <% if @warranty_claims.size !=0 %>
    <table class="table mt-3">
      <thead class="thead-dark">
        <tr>
          <th>S No</th>
          <th>Customer Name</th>
          <th>Product Name</th>
          <th>Description</th>
          <th>Current Status</th>
          <th>View claim</th>
          <th>Update Status</th>
        
        </tr>
      </thead>
      <tbody>
        <%i=0%>
        <% @warranty_claims.each do |claim| %>
          <% status = ClaimResolution.find_by(warranty_claim_id: claim.id) %>
          <% if ["In Progress", "Accepted", "Shipped"].include?(status.status) %>
            <tr class="table-active">
              <td><%= i= i + 1 %></td>
              <td><%= claim.invoice.customer.name %></td>
              <td><%= claim.invoice.product.name %></td>
              <td><%= claim.problem_description %></td>
              <td><%= status.status %></td>
                            <td><%= link_to 'view', warranty_claim_path(id: status.warranty_claim.id) , class: 'btn btn-primary' %></td>
              <td><%= link_to 'Update', claim_resolution_path(id: status.id) , class: 'btn btn-primary' %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
   <B> <p>Hurray!! , No pending Claims </p> </B>
  <% end %>
</div>

app/views/sellers/edit.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">Edit Sellers Profile</h1>
<%if @seller.errors.any?%>
    <% @seller.errors.full_messages.each do|message| %>
       <%flash.now[:alert]=message%>
    <%end%>
 <%end%>
<%=form_with model: @seller do|form|%>
<div class="form-group">
    <%= form.label :Name %>
    <%= form.text_field :name ,class: "form-control" %>
</div>

<div class="form-group">
     <%= form.label :Organisation %>
     <%= form.text_field :organisation_name ,class: "form-control" %>
</div>
<div class="form-group">
     <%= form.label :Designation %>
     <%= form.text_field :designation ,class: "form-control" %>
</div>
<%= link_to 'Back', :back, class: 'btn btn-secondary' %>

<%=form.submit "Update" , class: "btn btn-primary" , style:"margin-left: 20px"%>
<%end%>
</div>
</div>

app/views/sellers/index.html.erb
<div class="container">
<div class=col-lg-10>
<h1>Sellers Lists </h1>
<%= link_to 'New Seller',new_seller_path %>
<table>
    <thead>
        <tr>   <th>Id </th> <th>Name </th> <th>Email</th> <th colspan ="3"> Actions</th></tr>
    <thead>
    <tbody>
        <%@sellers.each do |seller| %>
       <tr>
        <td> <%= seller.id %> </td>
         <td> <%= seller.name %> </td>
         <td> <%= seller.email %> </td>
         <td> <%= link_to 'View',seller %> </td>
          <td> <%= link_to 'Edit', edit_seller_path(seller)  %> </td>
          
       </tr>
       <%end%> 
       <tr> <td> <%= link_to 'View Claim Tickets', claim_statuses_path()  %> </td></tr>
        <tr> <td> <%= link_to 'Products Section', products_path()  %> </td></tr>
    </tbody>
</table>
</div>

app/views/sellers/new.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">New Sellers Profile</h1>
<%= render "form" %>
</div>
</div>

app/views/sellers/show.html.erb
<div class="container">
<div class="col-lg-10 container" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 90px;margin-left:50px;">
  <h1 style="color: #fff;text-align: center;">Seller Details</h1>

   <p style="color: #fff; margin-left: 20px;"><strong>Name:</strong> <%= @seller.name %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Email:</strong> <%= @seller.email %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Organisation:</strong> <%= @seller.organisation_name %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Designation:</strong> <%= @seller.designation %></p>

  <div class="seller-details-actions" style="margin-top: 20px;">
    <%= link_to 'Back', seller_dashboard_path, class: 'btn btn-secondary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;' %>
    <%= link_to 'Edit', edit_seller_path(@seller), class: 'btn btn-primary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none; margin-left: 10px;' %>
  </div>
</div>
</div>