config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customer/dashboard" , controller: :customers , action: :dashboard , as: :cust_dashboard
    get "/seller/dashboard" , controller: :sellers , action: :dashboard , as: :seller_dashboard
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    get "/address/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions", controller: :claim_resolutions , action: :update 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims ,:addresses
  resources :claim_resolutions


  namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customers/customer_invoices" , controller: :customers , action: :customer_invoices , as: :cutomer_invoices
    get "/sellers/seller_products" , controller: :sellers , action: :seller_products , as: :seller_products
    get "/sellers/stats" , controller: :sellers , action: :stats , as: :stats
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    patch "/addresses/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions/default_claim_resolution" ,controller: :claim_resolutions,action: :default_claim_resolution,as: :default_claim_resolution
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims  ,:addresses
  resources :claim_resolutions
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :name , :email ,:phone_no, presence: true
    validates :name ,length: {minimum: 1, maximum: 25}
    validates :name, format: { with: /\A[A-Za-z\s.\-]+\z/, message: "only allows alphabets, spaces, dots, and hyphens" }

    validates :email ,uniqueness: true , format:{ with: /\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+/, message: 'please enter a valid email' }
    validates :phone_no ,length: {is: 10},numericality: true ,presence: true,format:{ with: /[9876]{1}\d{9}/, message: 'please enter a valid phone number' }
    validates :age, presence: true, numericality: { only_integer: true , greater_than: 5,less_than: 100}
    validates :gender , presence: true ,format: { with: /\A[a-z A-Z]+\z/, message: "only allows alphabets" }

    
    has_and_belongs_to_many :sellers ,join_table: :customers_sellers
    has_many :invoices , dependent: :destroy
    has_many :addresses, as: :addressable, dependent: :destroy
    has_many :products , through: :invoices
    has_many :warranty_claims , through: :invoices
    has_many :claim_resolutions, through: :warranty_claims
    has_one :user, as: :userable, dependent: :destroy
    
    scope :has_purchased, -> { joins(:invoices).distinct }
    scope :not_purchased, -> { left_outer_joins(:invoices).where(invoices: { id: nil }) }


end

app/controllers/api/customers_controller.rb
class Api::CustomersController < Api::ApiController
  #show all the customers in DB
    def index 
        customers=Customer.all
        if customers
        render json: customers, status: 200 #ok
        else
         render json: {message: "No Customers Found"}, status:204 #no_content
        end
    end

  #used to insert the new record in DB
    def create
      if customer
        customer=Customer.new(customer_params)
        if(customer.save)
            render json:customer , status: 200#created
        else
            render json:{error: customer.error.full_messages},status:422 #unprocessable_entity
        end
      else
        render json: {error: "No Customer found with  given  id #{params[:id]}"}
      end

    end
  #used to display aparticular record
    def show
        customer=Customer.find_by(id: params[:id])
        if customer
            if customer.id==current_user.userable_id
            render json: customer , status:200 #ok
            else
              render json:{message:"Forbidden Access to the profile"}, status:403 #forbidden
            end
        else
            render json:{message:"Customer Not Found"}, status:404 #not_found
        end

    end
  
  #saves the changes to DB
    def update
        customer=Customer.find_by(id: params[:id])
        if customer
          if customer.id==current_user.userable_id && current_user.customer?
            if(customer.update(customer_params))
              render json:customer , status:200
            else
              render json:{error: customer.errors.full_messages}, status:422 #unprocessable_entity
            end
          else
            render json:{message:"Forbidden Access to update the profile"}, status:403 #forbidden
          end
        else
            render json:{error: "No Customer Found with given Id#{params[:id]}"}, status:404 #not_found

        end
    end
  #deletes a record from DB
    def destroy
        customer=Customer.find_by(id: params[:id])
        if  customer
        if  current_user.userable_id==customer.id &&current_user.customer?
        
         if(customer.destroy)
            render json:{ message: "Customer Deleted successfully"},status:200 #ok
         else
            render json:{error: customer.errors.full_messages}, status:422#unprocessable_entity
         end
        else
            render json:{error: "Fobidden Access to delete the profile"}, status: 403

        end
      else
        render json: {error: "No Customer found with  given  id #{params[:id]}"}, status: 404
      end
    end

    def customer_invoices
     customer=Customer.find_by(id: current_user.userable_id)
    
      if  current_user.customer?
        invoices = customer.invoices
        if invoices
            render json:invoices , status:200
        else
            render json:{message:"No Invoices For given Customer Id #{params[:id]}"},status:204 #no_content

        end 
        
      else
        render json:{error: "Forbidden Access to update the profile"}, status: 403#forbidden
      end
   
    end

 private
    def customer_params
        params.require( :customer).permit(:name, :email,:age,:gender,:phone_no,:primary_address_id)
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  #show all the customers in DB
  before_action :authorize_customer, only: %i[  edit destroy dashboard ]
  
    def index 
        @customers=Customer.all
    end
  #used to instantiate a customer
    def new
        @customer=Customer.new

    end
  #used to insert the new record in DB
    def create
        @customer=Customer.new(customer_params)
        if(@customer.save)
            redirect_to change_primary_address_path
        else
            render :new
        end

    end
  #used to display aparticular record
    def show
        @customer=Customer.find_by(id: params[:id])
        unless current_user.userable == (@customer)
            flash[:notice] = "You are not authorized to perform this action."
            redirect_to root_path
        end
    end
  #used to fetch the record to edit
    def edit
        @customer=Customer.find_by(id: params[:id])
        unless current_user.userable == (@customer)
            flash[:notice] = "You are not authorized to perform this action."
            redirect_to root_path
        end
    end
  #saves the changes to DB
    def update
        
        @customer=Customer.find_by(id: params[:id])
        if(@customer.update(customer_params))
            render :show
        else
            render :edit 
        end
    end
  #deletes a record from DB
    def destroy
        @custome=current_user.userable
        if(@customer.destroy)
            redirect_to root_path
        else
            render :edit 
        end
    end

    def dashboard
        @invoices = current_user.userable.invoices

    end

 private
    def customer_params
        params.require( :customer).permit(:name, :email,:age,:gender,:phone_no)
    end

    def authorize_customer
        unless (user_signed_in? && current_user.customer?)
          flash[:notice] = "You are not authorized to perform this action."
          redirect_to root_path
        end
      end

end

app/views/customers/dashboard.html.erb
<div class="container">
   <b> <h1 class="mt-4">Welcome to the Customer Dashboard</h1> <b>
  
    
     
  <% if @invoices.size != 0 %>
      <h2 class="mt-4">Your Purchases</h2>
      <table class="table mt-3">
        <thead class="thead-dark">
          <tr >
            <th>S No</th>
            <th>Name</th>
            <th>Category</th>
            <th>Purchase Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
         <%i=0%>
         <% @invoices.each do |invoice| %>
  <% product = Product.find_by(id: invoice.product_id) %>
  <% claim = WarrantyClaim.find_by(invoice_id: invoice.id) %>
  <% resolution = invoice.claim_resolution %>
  <tr class ="table-active">
    <td><%= i= i + 1%></td>
    <td><%= product.name %></td>
    <td><%= product.category %></td>
    <td><%= invoice.purchase_date %></td>
    <td>
      <% if resolution.present? %>
        <% if ["Accepted", "In Progress", "Shipped"].include?(resolution.status) %>
          <%= link_to 'Track Status', claim_resolution_path(resolution), class: 'btn btn-primary' %>
        <% else %>
          <%= link_to "Claim #{resolution.status}", claim_resolution_path(resolution), class: 'btn btn-primary' %>
         <%end%>
      <%elsif invoice.purchase_date <1.year.ago%>
            <button type="button" class="btn btn-secondary btn" disabled>Claim Expired</button>
       <% else %>
          <%= link_to 'Claim Warranty', new_warranty_claim_path(id: invoice.id), class: 'btn btn-success' ,notice: 'Please note that the shipment will be delivered to your primary address.'%>
        <% end %>

               
             
    </td>
    </tr>
     <% end %>
        </tbody>
      </table>

    <% else %>
    <br> <br>
      <h4><b><p> Opps! No Products  Purchased </p><b></h4>
    <% end %>
  
    
  </div>
  

app/views/customers/edit.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">Edit Customer Profile</h1>
<%if @customer.errors.any?%>
    <% @customer.errors.full_messages.each do|message| %>
     <%flash.now[:alert]=message%>
    <%end%>
 <%end%>
<%=form_with model: @customer do|form|%>
<div class="form-group"> 
    <%= form.label :Name %>
    <%= form.text_field :name ,class: "form-control" %>
</div>

<div class="form-group">
     <%= form.label :Age %>
     <%= form.number_field :age ,class: "form-control" %>
</div>
<div class="form-group">
     <%= form.label :Gender %>
     <%= form.text_field :gender ,class: "form-control"%>
</div>
<div class="form-group"> 
     <%= form.label :Phone %>
     <%= form.number_field :phone_no ,class: "form-control" %>
</div>

  <%=link_to "Back" , customer_path(@customer), class: "btn btn-secondary", style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;'%>  
  <%=form.submit "Update", class:"btn btn-primary",style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none; margin-left: 10px'%>  
<%end%>
</div>
</div>

app/views/customers/index.html.erb
<div class="container">
<div class="col-lg-10" >
<h1>Customers Lists </h1>
<%= link_to 'New Customer',new_customer_path %>

<table>
    <thead>
        <tr>  <th>Name </th> <th>Email</th> <th colspan ="3"> Actions</th></tr>
    <thead>
    <tbody>
        <%@customers.each do |customer| %>
       <tr>
    
         <td> <%= customer.name %> </td>
         <td> <%= customer.email %> </td>
         <td> <%= link_to 'view ',customer %> </td>
          <td> <%= link_to 'Edit', edit_customer_path(customer)  %> </td>
          
       </tr>
       <%end%> 
    </tbody>
</table>
</div>
</div>

app/views/customers/new.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">New Customers  Profile</h1>
<%if @customer.errors.any?%>
    <% @customer.errors.full_messages.each do|message| %>
       <%flash.now[:alert]=message%>
    <%end%>
 <%end%>
<%=form_with model: @customer do|form|%>
<div>
    <%= form.label :Name %>
    <%= form.text_field :name %>
</div>
<div>
     <%= form.label :Email %>
     <%= form.email_field :email %>
</div>
<div>
     <%= form.label :Age %>
     <%= form.number_field :age %>
</div>
<div>
     <%= form.label :Gender %>
     <%= form.text_field :gender %>
</div>
<div>
     <%= form.label :Phone  %>
     <%= form.text_field :phone_no %>
</div>
<%=form.submit %>
<%end%>
</div>

app/views/customers/show.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 100px;">
  <h1 style="color: #fff; text-align: center;">Customer Details</h1>


  <p style="color: #fff; margin-left: 20px;"><strong>Name:</strong> <%= @customer.name %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Email:</strong> <%= @customer.email %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Age:</strong> <%= @customer.age %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Gender:</strong> <%= @customer.gender %></p>
  <p style="color: #fff; margin-left: 20px;"><strong>Phone:</strong> <%= @customer.phone_no %></p>

  <div style="margin-top: 20px;">
    <%= link_to 'Back', cust_dashboard_path, class: 'btn btn-secondary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;' %>
    <%= link_to 'Edit', edit_customer_path(@customer), class: 'btn btn-primary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none; margin-left: 10px;' %>
  </div>
</div>
</div>