config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customer/dashboard" , controller: :customers , action: :dashboard , as: :cust_dashboard
    get "/seller/dashboard" , controller: :sellers , action: :dashboard , as: :seller_dashboard
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    get "/address/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions", controller: :claim_resolutions , action: :update 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims ,:addresses
  resources :claim_resolutions


  namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    
    get "/customers/customer_invoices" , controller: :customers , action: :customer_invoices , as: :cutomer_invoices
    get "/sellers/seller_products" , controller: :sellers , action: :seller_products , as: :seller_products
    get "/sellers/stats" , controller: :sellers , action: :stats , as: :stats
    post "/invoice/generate" , controller: :invoices , action: :generate , as: :generate_invoice
    patch "/addresses/primary_address" , controller: :addresses , action: :primary_address , as: :primary_address
    get "/address/change_primary_address" , controller: :addresses , action: :change_primary_address , as: :change_primary_address
    patch "/claim_resolutions/default_claim_resolution" ,controller: :claim_resolutions,action: :default_claim_resolution,as: :default_claim_resolution
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home_pages#index'
  resources :customers
  resources :sellers
  resources :products
  resources :invoices
  resources :warranty_claims  ,:addresses
  resources :claim_resolutions
  end


end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :seller
    has_many :invoices, dependent: :destroy
   
    validates :name,:category , presence: true
  
    scope :sold, -> { joins(:invoices).distinct }
    scope :not_sold, -> { left_outer_joins(:invoices).where(invoices: { id: nil }) }
end

app/controllers/api/products_controller.rb
class Api::ProductsController < Api::ApiController
 before_action :set_product, only: %i[show update destroy]
           #show all the products in DB
           
         def index 
          
            products=current_user.userable.products
            if products
              render json: products, status: 200 #ok
              else
               render json: {message: "No products Found"}, status:204 #no_content
              end
          
         end
    
       #used to insert the new record in DB
         def create
             if current_user.seller?
               @product=Product.new(product_params)
               @product.seller_id=current_user.userable_id
               if(@product.save)
                render json:@product , status: 200#created
               else
                render json:{error: @product.errors.full_messages},status:422 #unprocessable_entity
               end
             else
              render json:{error: "Forbidden Access You Must be a seller"}, status: 403#forbidden
            end
     
         end
       #used to display a particular record
        def show

         if current_user.userable.products.include?(@product)
           if @product
             render json: @product , status:200 #ok
           else
             render json:{message:"Product Not Found for Id#{params[:id]}"}, status:404 #not_found
           end
         else
          render json:{error: "Forbidden Access to Product"}, status: 403#forbidden

          end

         end
       
       #saves the changes to DB
         def update
          if current_user.seller? && current_user.userable.products.include?(@product)
          if @product    
             if(@product.update(product_params))
                 render json:@product , status: 200#accepted
             else
                 render json:{error: @product.errors.full_messages}, status:422 #unprocessable_entity
             end
          else
            render json:{error: "No Product Found with given Id#{params[:id]}"}, status:404 #not_found
          end
        else
          render json:{error: "Forbidden Access to Product"}, status: 403

          end

         end
       #deletes a record from DB
         def destroy
          if current_user.seller? && current_user.userable.products.include?(@product) 
          if @product.invoices.length == 0
          
             
             if(@product.destroy)
               render json:{ message: "Product Deleted successfully"},status:200 #ok
             else
               render json:{error: @product.errors.full_messages}, status:422#unprocessable_entity
             end

          else
            render json:{error: "You can't delete products which has invoices"}, status: 403
          end
        else
          render json:{error: "Forbidden Access to Product"}, status: 403#forbidden

          end
         
        end
     
      private
         def set_product
             @product=Product.find_by(id: params[:id])
             if !@product
              render json:{error: "No Product Found with given Id #{params[:id]}"}, status: 404
              return
             end
         end
         def product_params
             params.require( :product).permit(:name, :category)
         end
     
end
   
        

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :set_product, only: %i[show edit update destroy]
           #show all the products in DB
           before_action :authenticate_user!
           before_action :authorize_seller, only: %i[ new index edit destroy ]
         def index 
            @products=current_user.userable.products
         end
       #used to instantiate a product
         def new
             @product=Product.new
         end
       #used to insert the new record in DB
         def create
             @product=Product.new(product_params)
             @product.seller_id=current_user.userable_id
             if(@product.save)
                 flash[:notice]="Product created successfully: "
                 redirect_to products_path 
             else
                 render :new
             end
     
         end
       #used to display a particular record
         def show
          unless current_user.userable.products.include?(@product)
            flash[:alert] = "You are not authorized to perform this action."
            redirect_to root_path
          end
         end
       #used to fetch the record to edit
         def edit
          unless current_user.userable.products.include?(@product)
            flash[:alert] = "You are not authorized to perform this action."
            redirect_to root_path
            return
          end

         end
       #saves the changes to DB
         def update
              @product.seller_id = current_user.userable_id
             if(@product.update(product_params))
                 render :show
             else
                 render :edit 
             end
         end
       #deletes a record from DB
         def destroy
          # unless current_user.userable.products.include?(@product)
          #   flash[:alert]= "You are not authorized to perform this action."
          #   redirect_to root_path
          #   return
          # end
           if @product.invoices.size !=0  
            flash[:alert]="Product Has been sold already"
           elsif(@product.destroy)
          
                flash[:notice]="Deleted successfully"
                 
           else
                 render :edit 
            end
            redirect_to products_path
         end
     
      private
         def set_product
             @product=Product.find_by(id: params[:id])
         end
         def product_params
             params.require( :product).permit(:name, :category)
         end

         def authorize_seller
          unless (user_signed_in? && current_user.seller?)
            flash[:alert]="You are not authorized to perform this action."
            redirect_to root_path
          end
        end
     
end
   
        

app/views/products/_form.html.erb
<%if @product.errors.any?%>
    <% @product.errors.full_messages.each do|message| %>
       <%flash.now[:alert]=message%>
    <%end%>
 <%end%>
<%=form_with model: @product do|form|%>
<div class="form-group">
   <strong> <%= form.label :Name %></strong>
    <%= form.text_field :name, class:"form-control" %>
</div>
<div class="form-group">
   <strong>  <%= form.label :Category %> </strong>
     <%= form.text_field :category,class:"form-control" %>
</div>

<%= link_to 'Back', :back, class: 'btn btn-secondary' %>

<%=form.submit "Create" , class: "btn btn-primary" , style:"margin-left: 20px"%>
<%end%>

app/views/products/edit.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">Edit Product</h1>
  <% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |message| %>
       <%flash.now[:alert]=message%>
    <% end %>
  <% end %>
  <%= form_with model: @product do |form| %>
    <div class="form-group">
     <strong> <%= form.label :Name %></strong>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <strong> <%= form.label :Category %></strong>
      <%= form.text_field :category, class: "form-control" %>
    </div>
  <%= link_to 'Back', :back, class: 'btn btn-secondary' %>

<%=form.submit "Update" , class: "btn btn-primary" , style:"margin-left: 20px"%>
  <% end %>
</div>
</div>

app/views/products/index.html.erb
<div class="container">
<div class="col-lg-10">
  <h1>Products List</h1>
 <h2> <%= link_to 'New Product', new_product_path, class: 'btn btn-success' %>
 </h2>
 
 <%if @products.size != 0 %>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>S.No</th>
        <th>Name</th>
        <th>Category</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
    <%i=0%>
      <% @products.each do |product| %>
        <tr class="table-active">
          <td><%= i= i+1 %></td>
          <td><%= product.name %></td>
          <td><%= product.category %></td>
          <td><%= link_to 'View', product, class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary' %></td>
          
          <td>
             <%if product.invoices.size == 0 %>
              <%= link_to 'Delete', product_path(product), method: :delete,  class: 'btn btn-danger'  %>   
             <%else%>
               <button type="button" class="btn btn-secondary btn-sm" disabled>Delete</button>     
             <%end%>               
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%else%>
      <h3>No Products Listed<h3>
  <%end%>
</div>
</div>

app/views/products/new.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">New Product</h1>


<%= render "form" %>\
</div>
</div>

app/views/products/show.html.erb
<div class="container">
<div class="col-lg-10" style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px; margin-top: 50px;">
  <h1 style="color: #fff; text-align: center;">Product Details</h1>
  <h4><p style="color: #fff;"><strong>Name:</strong> <%= @product.name %></p></h4>
  <h4><p style="color: #fff;"><strong>Category:</strong> <%= @product.category %></p></h4>
   <h4><p style="color: #fff;"><strong>Sold Units:</strong> <%= @product.invoices.count %></p></h4>

  <div style="text-align: center; margin-top: 20px;">
    <%= link_to 'Back', products_path, class: 'btn btn-primary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none;' %>
    <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none; margin-left: 10px;' %>
    <%= link_to 'Generate Invoice', new_invoice_path(id: @product.id), class: 'btn btn-success', style: 'background-color: charcoal; padding: 5px 20px; border-radius: 5px; border: none; color: #fff; text-decoration: none; margin-left: 10px;' %>
  </div>
</div>
</div>